apiVersion: v1
kind: Service
metadata:
  name: podinfo
spec:
  ports:
    - name: http
      port: 19898
      protocol: TCP
      targetPort: http
    - port: 19999
      targetPort: grpc
      protocol: TCP
      name: grpc