bases:
- ../../base
namePrefix: qa-
namespace: qa-podinfo
resources:
  - namespace.yaml
# images:
# - name: ghcr.io/stefanprodan/podinfo
#   newTag: 6.3.1
patchesStrategicMerge:
  - promotion/app-version.yaml
patches:
  - path: no-promotion/service.patch.yaml
    target:
      version: v1
      kind: Service
      name: podinfo
