bases:
- ../../base
namePrefix: prod-
namespace: prod-podinfo
resources:
  - namespace.yaml
# images:
# - name: ghcr.io/stefanprodan/podinfo
#   newTag: 6.3.1
patchesStrategicMerge:
  - promotion/app-version.yaml
patches:
  - path: no-promotion/service.yaml
