apiVersion: v1
kind: Service
metadata:
  name: podinfo
spec:
  # type: ClusterIP
  type: LoadBalancer
  selector:
    app: podinfo
  ports:
    - name: http
      port: 39898
      protocol: TCP
      targetPort: http
    - port: 39999
      targetPort: grpc
      protocol: TCP
      name: grpc